### ISSUE TITLE
Only scrape when asked

### ISSUE THREAD

**Issue by xonvanetta** [clambin/upnp-exporter#10]
According to [prometheus docs](https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling):
>Metrics should only be pulled from the application when Prometheus scrapes them, exporters should not perform scrapes based on their own timers. That is, all scrapes should be synchronous.

I could help with a PR, later if that would be fine

**Comment by clambin** [comment]
thanks for offering to do a PR, but was on my backlog anyway. :)
